# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Northern Latitudes
email: hello@northernlatitudes.org
description: >
  Alaska-based Landscape Conservation Cooperatives and Alaska
  Climate Science Center
github:
  url: http://localhost:4000
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://northern-latitudes.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  northern-latitudes

# Build settings
markdown: kramdown
