# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Northern Latitudes
email: hello@northernlatitudes.org
description: >
  Alaska-based Landscape Conservation Cooperatives and Alaska
  Climate Science Center
github:
  #url: http://localhost:4000
  url: http://northernlatitudes.org
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://northernlatitudes.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  northern-latitudes

# Build settings
markdown: kramdown
encoding: utf-8

permalink: pretty

prose:
  rooturl: '_posts'
  siteurl: 'http://northernlatitudes.org'
  relativeLinks: 'http://northernlatitudes.org/links.jsonp'
  media: 'assets/media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: CURRENT_DATETIME
      - name: "icon"
        field:
          element: "select"
          label: "Logo"
          placeholder: "Choose Tags"
          options:
            - name: "Default"
              value: ""
            - name: "ABSI"
              value: "absi"
            - name: "Arctic"
              value: "arctic"
            - name: "AKCSC"
              value: "csc"
            - name: "North Pacific"
              value: "np"
            - name: "NWB"
              value: "nwb"
            - name: "Western AK"
              value: "wa"
      - name: "tags"
        field:
          element: "text"
          label: "Add Tags"
          value: "announcement"
